namespace: community
name: rabbitmq
version: 0.1.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
  - community.rabbitmq (https://github.com/ansible-collections/rabbitmq/graphs/contributors)
description: null
license: GPL-3.0-or-later
license_file: LICENSE
tags:
  - messaging
dependencies: {}
repository: https://github.com/ansible-collections/rabbitmq
documentation: https://github.com/ansible-collections/rabbitmq/README.md
homepage: https://github.com/ansible-collections/rabbitmq
issues: https://github.com/ansible-collections/rabbitmq/issues
